### ISSUE TITLE
Erro link de pagamento

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/integration-rede-for-woocommerce#50]
Clientes estão informando que estão acontecendo alguns erros com os temas

[Hello Elementor](https://br.wordpress.org/themes/hello-elementor/)
[OceanWP](https://br.wordpress.org/themes/oceanwp/)

Outros estão tendo problemas com o link de pagamento (fatura) e os campos não estão sendo renderizados de forma correta para a opção crédito. [Link do fórum com mais detalhes](https://wordpress.org/support/topic/versao-3-0-do-plugin-com-erros/#post-17770185).

Erro apresentado via JS:
```
Mensagem de erro do Web Developer:

jquery.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading ‘dispatchEvent’)
at wooRedeCredit.js:53:21
at Array.forEach ()
at HTMLDocument. (wooRedeCredit.js:52:45)
at e (jquery.min.js:2:27028)
at t (jquery.min.js:2:27330)

jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading ‘dispatchEvent’) TypeError: Cannot read properties of undefined (reading ‘dispatchEvent’) at /wp-content/plugins/woo-rede/Public/js/creditCard/rede/wooRedeCredit.js:53:21 at Array.forEach (<anonymous>) at HTMLDocument.<anonymous> (/wp-content/plugins/woo-rede/Public/js/creditCard/rede/wooRedeCredit.js:52:45) at e (/wp-includes/js/jquery/jquery.min.js:2:27028) at t (/wp-includes/js/jquery/jquery.min.js:2:27330) [undefinedce.Deferred.exceptionHook@jquery.min.js](mailto:undefinedce.Deferred.exceptionHook@jquery.min.js):2
```

**Comment by emanuellopess** [comment]
Corrigido no PR #52
